M2 gatk4.1.2.0 updates and gatk3.8 CombineVariants for Strelka and all callers
biowdl/somatic-variantcalling pull request #14
Opened 2019-08-06 18:09 UTC by Amfgcp

### Checklist
- [X] Pull request details were added to CHANGELOG.md

2019-08-06 19:34 UTC, Amfgcp commented
Need to re-write CombineVariants gatk task so it is more general, e.g., when not all callers are run.

2019-08-08 13:59 UTC, Amfgcp commented
Changed CombineVariants to not run by default. Now it will only run if:
- The corresponding input parameter is set to true
- All 3 variant callers were run
- Strelka outputs a combined VCF file (which now only happens if VCFs for manta, indels and variants are generated).

This implementation does not generalize well, e.g., it is not possible to run only 1 or 2 variant callers and expect to have their VCFs combined in the end. It was only thought to work when running all 3 variant callers and Strelka with manta, indels and variants.

2019-08-09 08:42 UTC, DavyCats approved these changes

2019-08-09 08:43 UTC, DavyCats requested changes
On second thought, could you add some test for these combined VCFs?

2019-08-09 11:43 UTC, DavyCats approved these changes

2019-08-09 13:50 UTC, merged